### PR TITLE
New Inbox and connection

### PR DESCRIPTION
**Pull request by roycem90**
1. Connection Class - Single point reference to any authentication, so no need to pass auth info everywhere and it allows configuring proxy as well

2. FluentInbox Class - A new format of inbox, with extra option, please have a look at readme.md for example code

3. fluent_message.py - Just added as a reference to enable the Connection based changes (right now its just copy of message.py with few additions, will be adding up stuff soon - if you like my way of coding)

### CODE REVIEW

**Comment by Narcolapser** [comment]
Interesting. I'll have to consider this. I think I like the idea but I might want to apply it to the other objects and integrate it into the existing inbox instead of having separate classes. I'll try to get back to you sooner than later, but probably not before thanks giving.

**Comment by roycem90** [comment]
i added it as another class, to make sure it doesn't effect existing users (as the api is completely different).. (^_^)

**Comment by janscas** [comment]
This is great @roycem90.

A big problem here is that Basic Auth is deprected on November 2018. Any ideas on how to implement the new Oauth authentication?

**Comment by Narcolapser** [comment]
Really? Basic Auth is going away? well, we will really have to get on issue #16. eep!

**Comment by roycem90** [comment]
Thats bad, will try to look at oauth this week

**Comment by Narcolapser** [comment]
how does fluent inbox handle multiple inboxes?

**Comment by roycem90** [comment]
not sure i understand the question, what do u mean by multiple inboxes?
multiple instances of the inbox class? or multiple mail id inbox (using same creds)?

**Comment by roycem90** [comment]
working on oauth2
code working as of now, will push up after some testing

**Comment by janscas** [comment]
@roycem90 Anywhere where I can see the code with oauth2 working?

**Comment by roycem90** [comment]
sorry, my laptop got a bunch of problems, just now got it fixed, i just commited the code on my master branch (u have the readme too)

**Comment by janscas** [comment]
Ok, but it is not using the Connection class either. It is using the old auth

**Comment by roycem90** [comment]
Shit looks like i overwrote the changes :(, but it was working when i tested.. 

Let me switch back my os and check

**Comment by roycem90** [comment]
okie, my mistake
1. there was a minor bug, fixed it
2. the message is still not updated to use the whole connection thing, but it works as of now

Below is the code i used and it got the message subjects

from O365 import Connection, FluentInbox

client_id = <YOUR_CLIENT_ID>
client_secret = <YOUR_CLIENT_SECRET>

Connection.oauth2(client_id, client_secret)

# Create an inbox reference
inbox = FluentInbox()

# Fetch 20 messages from "Temp" folder containing "Test" in the subject
for message in inbox.from_folder('Inbox').search('Subject:Test').fetch(count=20):
    # Just print the message subject
    print(message.getSubject())

**Comment by Narcolapser** [comment]
Would you say this is ready to merge in as is? I've looked it over and it seems fine. It looks like you've danced very carefully around the existing code to avoid breaking backwards compatibility. If so I think I'll go ahead an merge it and push a new version to pypi. I have some ideas I'd like to discuss with you on the topic of this. I'll send you a PM in a bit.

**Comment by roycem90** [comment]
Yup, its ready to be merged, no impact on the existing code 💯

**Comment by Narcolapser** [comment]
Github removed private messaging. oh well, I made a gist instead. Which will probably be better, this way if anyone wants to join the conversation they can. 

https://gist.github.com/Narcolapser/af9cb33e735049819c54b71de6b4963a

**Comment by janscas** [comment]
I'll like to contribute and find the structure you detail on the gist very suitable.
@roycem90 in the connection.py, future.utils is only python2. This should work on python 3.

**Comment by roycem90** [comment]
@janscas, ya i added that only for compatibility with python 2

**Comment by Narcolapser** [comment]
Alright. that took a little more than expected to merge because the web editor was broken for some reason. *shrug* anyway. It's in now. Thanks for the contribution.

@both of you. I'll make a new milestone and open issues for working on this. I'm glad to have both of you contributing. I'll try to get on it as soon as possible. But you know, life never goes as planned. xD

**Comment by roycem90** [comment]
👍

**Pull request merged**
